apiVersion: v1
kind: Service
metadata:
  name: result-app-vote-service
spec:
  selector:
    name: voting-app-result
    app: demo-voting-app
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 8181
  