apiVersion: v1
kind: Pod
metadata:
  name: voting-app-result
  labels:
    name: voting-app-result
    app: demo-voting-app
spec:
  containers:
  - name: votting-result-app
    image: docker/example-voting-app-result
    ports:
      - containerPort: 80
