apiVersion: v1
kind: Pod
metadata:
  name: voting-app-vote
  labels:
    name: voting-app-vote
    app: demo-voting-app
spec:
  containers:
  - name: votting-demo-app
    image: docker/example-voting-app-vote
    ports:
      - containerPort: 80
