apiVersion: v1
kind: Pod
metadata:
  name: voting-app-worker
  labels:
    name: voting-app-worker
    app: demo-voting-app
spec:
  containers:
  - name: voting-app-worker
    image: docker/example-voting-app-worker
